package com.meftaul.aurum.domain;

import static com.meftaul.aurum.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AurumServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAurumServiceAllPropertiesEquals(AurumService expected, AurumService actual) {
        assertAurumServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertAurumServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAurumServiceAllUpdatablePropertiesEquals(AurumService expected, AurumService actual) {
        assertAurumServiceUpdatableFieldsEquals(expected, actual);
        assertAurumServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAurumServiceAutoGeneratedPropertiesEquals(AurumService expected, AurumService actual) {
        assertThat(actual)
            .as("Verify AurumService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAurumServiceUpdatableFieldsEquals(AurumService expected, AurumService actual) {
        assertThat(actual)
            .as("Verify AurumService relevant properties")
            .satisfies(a -> assertThat(a.getServiceType()).as("check serviceType").isEqualTo(expected.getServiceType()))
            .satisfies(a -> assertThat(a.getItemName()).as("check itemName").isEqualTo(expected.getItemName()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getWeight()).as("check weight").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeight())
            )
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getKaratType()).as("check karatType").isEqualTo(expected.getKaratType()))
            .satisfies(a -> assertThat(a.getExpectedKaratType()).as("check expectedKaratType").isEqualTo(expected.getExpectedKaratType()))
            .satisfies(a -> assertThat(a.getAddedAlloy()).as("check addedAlloy").isEqualTo(expected.getAddedAlloy()))
            .satisfies(a ->
                assertThat(a.getAlloyQuantity())
                    .as("check alloyQuantity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAlloyQuantity())
            )
            .satisfies(a ->
                assertThat(a.getServiceCharge())
                    .as("check serviceCharge")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getServiceCharge())
            )
            .satisfies(a ->
                assertThat(a.getFreeCheck()).as("check freeCheck").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFreeCheck())
            )
            .satisfies(a -> assertThat(a.getHallMarkedText()).as("check hallMarkedText").isEqualTo(expected.getHallMarkedText()))
            .satisfies(a -> assertThat(a.getWeightOfFreeCheck()).as("check weightOfFreeCheck").isEqualTo(expected.getWeightOfFreeCheck()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAurumServiceUpdatableRelationshipsEquals(AurumService expected, AurumService actual) {
        assertThat(actual)
            .as("Verify AurumService relationships")
            .satisfies(a -> assertThat(a.getVoucher()).as("check voucher").isEqualTo(expected.getVoucher()));
    }
}
