package com.meftaul.aurum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllPropertiesEquals(Item expected, Item actual) {
        assertItemAutoGeneratedPropertiesEquals(expected, actual);
        assertItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllUpdatablePropertiesEquals(Item expected, Item actual) {
        assertItemUpdatableFieldsEquals(expected, actual);
        assertItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAutoGeneratedPropertiesEquals(Item expected, Item actual) {
        assertThat(actual)
            .as("Verify Item auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableFieldsEquals(Item expected, Item actual) {
        assertThat(actual)
            .as("Verify Item relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableRelationshipsEquals(Item expected, Item actual) {
        // empty method
    }
}
