package com.meftaul.aurum.domain;

import static com.meftaul.aurum.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class KaratAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKaratAllPropertiesEquals(Karat expected, Karat actual) {
        assertKaratAutoGeneratedPropertiesEquals(expected, actual);
        assertKaratAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKaratAllUpdatablePropertiesEquals(Karat expected, Karat actual) {
        assertKaratUpdatableFieldsEquals(expected, actual);
        assertKaratUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKaratAutoGeneratedPropertiesEquals(Karat expected, Karat actual) {
        assertThat(actual)
            .as("Verify Karat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKaratUpdatableFieldsEquals(Karat expected, Karat actual) {
        assertThat(actual)
            .as("Verify Karat relevant properties")
            .satisfies(a -> assertThat(a.getKaratType()).as("check karatType").isEqualTo(expected.getKaratType()))
            .satisfies(a ->
                assertThat(a.getPurityPercent())
                    .as("check purityPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPurityPercent())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKaratUpdatableRelationshipsEquals(Karat expected, Karat actual) {
        // empty method
    }
}
