package com.meftaul.aurum.domain;

import static com.meftaul.aurum.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRateAllPropertiesEquals(Rate expected, Rate actual) {
        assertRateAutoGeneratedPropertiesEquals(expected, actual);
        assertRateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRateAllUpdatablePropertiesEquals(Rate expected, Rate actual) {
        assertRateUpdatableFieldsEquals(expected, actual);
        assertRateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRateAutoGeneratedPropertiesEquals(Rate expected, Rate actual) {
        assertThat(actual)
            .as("Verify Rate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRateUpdatableFieldsEquals(Rate expected, Rate actual) {
        assertThat(actual)
            .as("Verify Rate relevant properties")
            .satisfies(a -> assertThat(a.getRateType()).as("check rateType").isEqualTo(expected.getRateType()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRateUpdatableRelationshipsEquals(Rate expected, Rate actual) {
        // empty method
    }
}
