package com.meftaul.aurum.domain;

import static com.meftaul.aurum.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAllPropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertTransactionHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAllUpdatablePropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertTransactionHistoryUpdatableFieldsEquals(expected, actual);
        assertTransactionHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryAutoGeneratedPropertiesEquals(TransactionHistory expected, TransactionHistory actual) {
        assertThat(actual)
            .as("Verify TransactionHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryUpdatableFieldsEquals(TransactionHistory expected, TransactionHistory actual) {
        assertThat(actual)
            .as("Verify TransactionHistory relevant properties")
            .satisfies(a -> assertThat(a.getVoucherNo()).as("check voucherNo").isEqualTo(expected.getVoucherNo()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getDateCreated()).as("check dateCreated").isEqualTo(expected.getDateCreated()))
            .satisfies(a -> assertThat(a.getTag()).as("check tag").isEqualTo(expected.getTag()))
            .satisfies(a -> assertThat(a.getCustomerId()).as("check customerId").isEqualTo(expected.getCustomerId()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionHistoryUpdatableRelationshipsEquals(TransactionHistory expected, TransactionHistory actual) {
        // empty method
    }
}
