package com.meftaul.aurum.domain;

import static com.meftaul.aurum.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VoucherAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAllPropertiesEquals(Voucher expected, Voucher actual) {
        assertVoucherAutoGeneratedPropertiesEquals(expected, actual);
        assertVoucherAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAllUpdatablePropertiesEquals(Voucher expected, Voucher actual) {
        assertVoucherUpdatableFieldsEquals(expected, actual);
        assertVoucherUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherAutoGeneratedPropertiesEquals(Voucher expected, Voucher actual) {
        assertThat(actual)
            .as("Verify Voucher auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherUpdatableFieldsEquals(Voucher expected, Voucher actual) {
        assertThat(actual)
            .as("Verify Voucher relevant properties")
            .satisfies(a -> assertThat(a.getVoucherNo()).as("check voucherNo").isEqualTo(expected.getVoucherNo()))
            .satisfies(a -> assertThat(a.getCustomerId()).as("check customerId").isEqualTo(expected.getCustomerId()))
            .satisfies(a ->
                assertThat(a.getCalculatedTotalAmount())
                    .as("check calculatedTotalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCalculatedTotalAmount())
            )
            .satisfies(a -> assertThat(a.getVat()).as("check vat").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getVat()))
            .satisfies(a ->
                assertThat(a.getDisountAmount())
                    .as("check disountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDisountAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalPayableAmount())
                    .as("check totalPayableAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalPayableAmount())
            )
            .satisfies(a -> assertThat(a.getDateCreated()).as("check dateCreated").isEqualTo(expected.getDateCreated()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()))
            .satisfies(a -> assertThat(a.getBoxNumber()).as("check boxNumber").isEqualTo(expected.getBoxNumber()))
            .satisfies(a -> assertThat(a.getDeliveryDate()).as("check deliveryDate").isEqualTo(expected.getDeliveryDate()))
            .satisfies(a -> assertThat(a.getDeliveryStatus()).as("check deliveryStatus").isEqualTo(expected.getDeliveryStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoucherUpdatableRelationshipsEquals(Voucher expected, Voucher actual) {
        // empty method
    }
}
